#include <stdint.h>

// options to control how MicroPython is built

// ooFatFs (MicroPython's bundled FatFs fork) requires FFCONF_H to point at the
// correct configuration header. Without this, builds may accidentally pick up a
// different ffconf.h from other middleware (eg TinyUSB), causing:
//   ff.h: error: Wrong configuration file (ffconf.h).
#define FFCONF_H "lib/oofatfs/ffconf.h"

// Enable a reasonably complete feature set (standard modules) while still
// keeping hardware/network/filesystem features explicitly opt-in for this
// project.
#define MICROPY_CONFIG_ROM_LEVEL (MICROPY_CONFIG_ROM_LEVEL_EXTRA_FEATURES)

// Core runtime features
#define MICROPY_ENABLE_GC                 (1)
#define MICROPY_ENABLE_COMPILER           (1)

// Needed for `marshal.loads()` (mp_raw_code_load_mem).
#define MICROPY_PERSISTENT_CODE_LOAD      (1)

// Run MicroPython in a single-VM/single-thread configuration for now.
// The project runs MicroPython inside a ThreadX thread, but does not yet
// integrate MicroPython's own thread/GIL subsystem (mp_thread_*).
// Keeping this off avoids per-thread MP_STATE corruption that can lead to
// nlr_jump_fail during exception unwinding.
#define MICROPY_PY_THREAD                 (0)
#define MICROPY_PY_THREAD_GIL             (0)

// Float/complex are needed for math/cmath.
#define MICROPY_FLOAT_IMPL                (MICROPY_FLOAT_IMPL_FLOAT)
#define MICROPY_PY_BUILTINS_FLOAT         (1)
#define MICROPY_PY_BUILTINS_COMPLEX       (1)

// Frozen .mpy produced by the in-tree mpy-cross expects MPZ long-int support.
// Enable MPZ so frozen bytecode is compatible with this firmware build.
#define MICROPY_LONGINT_IMPL              (MICROPY_LONGINT_IMPL_MPZ)

// Enable the VFS framework. Actual storage (SD/flash block device) will be
// brought up incrementally; enabling VFS first lets us expose VfsFat and the
// mount API.
#define MICROPY_VFS                       (1)
// Use VFS-backed file reader so `import foo.py` and `exec(open(...))` can read
// from mounted filesystems.
#define MICROPY_READER_VFS                (1)
// Start with FAT VFS (works well with SD cards and is PC-friendly).
#define MICROPY_VFS_FAT                   (1)
// Enable relative paths and getcwd/chdir support in ooFatFs.
#define MICROPY_FATFS_RPATH               (2)

// FAT sector size (used by ooFatFs and also as the TinyUSB MSC endpoint buffer size).
// SD cards use 512-byte logical sectors.
#ifndef MICROPY_FATFS_MAX_SS
#define MICROPY_FATFS_MAX_SS              (512)
#endif
// LittleFS is not enabled yet (requires bringing in lib/littlefs sources and a
// flash block device driver).
#define MICROPY_VFS_LFS1                  (0)
#define MICROPY_VFS_LFS2                  (0)

// Enable the C-backed `socket` module, but keep lwIP and any actual NIC drivers
// disabled for now. This makes `import socket` work and is a stepping stone to
// a real network bring-up.
#define MICROPY_PY_NETWORK                (1)
// Enable MicroPython's generic (non-lwIP) network interface layer.
// Without this, extmod/modnetwork.h does not define the socket types used by
// extmod/modsocket.c when MICROPY_PY_LWIP=0.
#define MICROPY_PORT_NETWORK_INTERFACES
#define MICROPY_PY_LWIP                   (0)
#define MICROPY_PY_SOCKET                 (1)
// Enable the CPython-style `ssl` module backed by mbedTLS.
// (Requires wiring mbedTLS sources + config into the build.)
#define MICROPY_PY_SSL                    (1)
#define MICROPY_SSL_MBEDTLS               (1)

// Keep the legacy `ussl` alias/module off for now.
#define MICROPY_PY_USSL                   (0)

// Required by extmod/modnetwork.c when MICROPY_PY_NETWORK is enabled.
// Must be a string literal.
#ifndef MICROPY_PY_NETWORK_HOSTNAME_DEFAULT
#define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "micropython"
#endif
// You can disable the built-in MicroPython compiler by setting the following
// config option to 0.  If you do this then you won't get a REPL prompt, but you
// will still be able to execute pre-compiled scripts, compiled with mpy-cross.
// You can disable the built-in MicroPython compiler by setting the following
// config option to 0.  If you do this then you won't get a REPL prompt, but you
// will still be able to execute pre-compiled scripts, compiled with mpy-cross.
#define MICROPY_ENABLE_COMPILER     (1)

// Frozen modules: include .mpy content in the firmware image.
#define MICROPY_MODULE_FROZEN_MPY         (1)
#define MICROPY_ENABLE_EXTERNAL_IMPORT    (1)

// Use the QSTR pool generated by mpy-tool when freezing .mpy modules.
// This enables QSTRs referenced by frozen bytecode (eg "gzip.py", "zlib.py").
#if MICROPY_MODULE_FROZEN_MPY
#define MICROPY_QSTR_EXTRA_POOL           mp_qstr_frozen_const_pool
#endif

#if MICROPY_MODULE_FROZEN_MPY && !defined(MICROPY_QSTR_EXTRA_POOL)
#error "MICROPY_MODULE_FROZEN_MPY requires MICROPY_QSTR_EXTRA_POOL (frozen QSTR pool)"
#endif

#define MICROPY_HELPER_REPL               (1)

#define MICROPY_ALLOC_PATH_MAX            (256)

// Use the minimum headroom in the chunk allocator for parse nodes.
#define MICROPY_ALLOC_PARSE_CHUNK_INIT    (16)

// sys module (and the legacy aliases usys, uos, utime, ...)
#define MICROPY_PY_SYS                    (1)
#define MICROPY_PY_SYS_MODULES            (1)
#define MICROPY_PY_SYS_EXIT               (1)
#define MICROPY_PY_SYS_PATH               (1)
#define MICROPY_PY_SYS_ARGV               (1)

// `marshal` needs access to a code object's constants/proto_fun.
// Ensure code objects include that metadata.
#define MICROPY_PY_BUILTINS_CODE          (MICROPY_PY_BUILTINS_CODE_BASIC)

// Standard modules (C built-ins)
#define MICROPY_PY_MATH                   (1)
#define MICROPY_PY_CMATH                  (1)
#define MICROPY_PY_OS                     (1)
#define MICROPY_PY_TIME                   (1)
#define MICROPY_PY_JSON                   (1)
#define MICROPY_PY_BINASCII               (1)
#define MICROPY_PY_UCTYPES                (1)
#define MICROPY_PY_RE                     (1)
#define MICROPY_PY_SELECT                 (1)
#define MICROPY_PY_RANDOM                 (1)
#define MICROPY_PY_HEAPQ                  (1)
#define MICROPY_PY_HASHLIB                (1)
#define MICROPY_PY_CRYPTOLIB              (1)
#define MICROPY_PY_MARSHAL                (1)
#define MICROPY_PY_ZLIB                   (1)
#define MICROPY_PY_ASYNCIO                (1)

// --- USB Device (TinyUSB) ---------------------------------------------------
// Expose the SD card as a USB Mass Storage device (MSC) so Windows can mount it
// as a drive when the board is connected over USB.
// Note: This is a minimal bring-up. Avoid simultaneous writes from both the MCU
// and the host PC to prevent filesystem corruption.
#define MICROPY_HW_ENABLE_USBDEV          (1)
#define MICROPY_HW_ENABLE_USB_RUNTIME_DEVICE (0)
#define MICROPY_HW_USB_CDC                (0)
#define MICROPY_HW_USB_MSC                (1)

// USB VID/PID: for real products you must use your own assigned VID/PID.
// These placeholder values are intended for local development/testing only.
#ifndef MICROPY_HW_USB_VID
#define MICROPY_HW_USB_VID                (0xCafe)
#endif
#ifndef MICROPY_HW_USB_PID
#define MICROPY_HW_USB_PID                (0x4010)
#endif

// TinyUSB target selection for STM32F405 (USB OTG FS uses Synopsys DWC2 core).
#define CFG_TUSB_MCU                      (OPT_MCU_STM32F4)
// DWC2 driver requires either slave or DMA mode; slave mode is simplest.
#define CFG_TUD_DWC2_SLAVE_ENABLE         (1)
#define CFG_TUD_DWC2_DMA_ENABLE           (0)

// micropython-specific libraries (incremental bring-up)
// btree is the unix/posix Berkeley-DB binding and depends on POSIX headers
// (eg fcntl.h) and a posix-style stream layer. Keep it off for this bare-metal
// ThreadX port until VFS/storage is brought up with an embedded-friendly backend.
#define MICROPY_PY_BTREE                  (0)

// Provide a minimal `machine` module first (reset/unique_id/freq/idle).
// Peripheral classes (Pin/UART/SPI/I2C/...) will be enabled in later steps.
#define MICROPY_PY_MACHINE                (1)
#define MICROPY_PY_MACHINE_INCLUDEFILE    "py_port/modmachine_port.c"
#define MICROPY_PY_MACHINE_RESET          (1)
#define MICROPY_PY_MACHINE_BARE_METAL_FUNCS (1)
#define MICROPY_PY_MACHINE_BOOTLOADER     (0)
// Keep all peripheral classes off for now to avoid needing pin/peripheral glue.
#define MICROPY_PY_MACHINE_PIN            (0)
#define MICROPY_PY_MACHINE_UART           (0)
#define MICROPY_PY_MACHINE_I2C            (0)
#define MICROPY_PY_MACHINE_SPI            (0)
#define MICROPY_PY_MACHINE_ADC            (0)
#define MICROPY_PY_MACHINE_PWM            (0)
#define MICROPY_PY_MACHINE_TIMER          (0)
#define MICROPY_PY_MACHINE_WDT            (0)

// These are hardware/stack dependent and will be enabled later.
#define MICROPY_PY_BLUETOOTH              (0)
#define MICROPY_PY_OPENAMP                (0)

// Temporarily disable `platform` until the build/genhdr setup is fully stable.
// This module is not essential for the initial “standard modules” milestone.
#define MICROPY_PY_PLATFORM                (1)

// type definitions for the specific machine

typedef intptr_t mp_int_t; // must be pointer size
typedef uintptr_t mp_uint_t; // must be pointer size
typedef long mp_off_t;

// Some bare-metal C libraries don't provide SSIZE_MAX (POSIX).  MicroPython's
// core defaults MP_SSIZE_MAX to SSIZE_MAX, so define MP_SSIZE_MAX here.
#ifndef MP_SSIZE_MAX
// Must be usable in preprocessor expressions (mpconfig.h uses it in #if).
// On this STM32F4/ARMClang build, mp_int_t is 32-bit.
#define MP_SSIZE_MAX (0x7fffffff)
#endif

// Provide alloca() in a way that works across embedded toolchains.
// Keil/ARM toolchains typically don't ship <alloca.h>.
#if defined(_MSC_VER)
	#include <malloc.h>
	#define alloca _alloca
#elif defined(__clang__) || defined(__GNUC__) || defined(__ARMCOMPILER_VERSION) || defined(__CC_ARM) || defined(__ARMCC_VERSION)
	#define alloca __builtin_alloca
#else
	#include <alloca.h>
#endif

#define MICROPY_HW_BOARD_NAME "PYBASE"
#define MICROPY_HW_MCU_NAME "STM32F405RG6"

#if defined(__linux__) || defined(__APPLE__)
#define MICROPY_MIN_USE_STDOUT (1)
#define MICROPY_HEAP_SIZE      (25600) // heap size 25 kilobytes
#endif

#ifdef __thumb__
// When building this STM32 project with Keil/ARMClang, startup and vector table
// are provided by the project startup assembly (startup_stm32f407xx.s).
// The minimal port's built-in Reset_Handler/vector table conflicts with that
// and also uses patterns not accepted by ARMClang for naked functions.
#if defined(__CC_ARM) || defined(__ARMCC_VERSION) || defined(__ARMCOMPILER_VERSION)
#define MICROPY_MIN_USE_CORTEX_CPU (0)
#else
#define MICROPY_MIN_USE_CORTEX_CPU (1)
#endif

#define MICROPY_MIN_USE_STM32_MCU (1)
#define MICROPY_HEAP_SIZE      (32768) // heap size 32 kilobytes
#endif

#define MP_STATE_PORT MP_STATE_VM

#define MP_ENDIANNESS_LITTLE (1)
// Use native ARM Thumb NLR implementation (see py/nlrthumb.c).
// The setjmp/longjmp implementation is often not robust on Cortex-M bare-metal/RTOS toolchains
// (especially with LTO/optimisations), and can lead to corrupted nlr_top and nlr_jump_fail.
#define MICROPY_NLR_SETJMP (0)
// Collect GC root registers using the port's assembly helper, not setjmp.
#define MICROPY_GCREGS_SETJMP (0)
#define MP_UNREACHABLE for (;;);
#define MICROPY_USE_INTERNAL_ERRNO (1)

